# Generated by Django 5.2.1 on 2025-05-11 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimator",
            name="trade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estimators",
                to="estimator.trade",
            ),
        ),
    ]
