# Generated by Django 5.2.1 on 2025-05-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
