# Generated by Django 5.2.1 on 2025-05-11 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0002_alter_trade_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("number_of_resources", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
